---
node_version: "24.21.0"
node_architecture_map:
  x86_64: x64
  aarch64: arm64
node_checksum_map:
  x86_64: fd8e59d5a511510f6a298afb548f18c7d2b1be404d8b4a27d94fbe49f56cb2d6
  aarch64: 6ad1325edbdb5649c379b75a237147a666c95d4f9ae8d340fef2d1575d289ad2
node_architecture: "{{ node_architecture_map[ansible_facts['architecture']] }}"
node_archive: "node-v{{ node_version }}-linux-{{ node_architecture }}.tar.xz"
node_directory: "/opt/node-v{{ node_version }}-linux-{{ node_architecture }}"

bench_cli_directory: /opt/bench/cli
bench_cli_system_config: /etc/bench/config.json
