---
- name: Create the projects directory
  ansible.builtin.file:
    path: "{{ bench_home }}/Sites"
    state: directory
    owner: "{{ bench_user }}"
    group: "{{ bench_primary_group }}"
    mode: "0755"
